#Configuration of Cluster includes node Id and node IP address
# serverNodes:
#nodeId:ipAddress
# 172.17.0.1: 
#   port: 6388
localtest1:
  ip: 127.0.1.1
  port: 6387
localtest2:
  ip: 127.0.1.1
  port: 6388
localtest3:
  ip: 127.0.1.1
  port: 6386